# Dialyzer warnings reviewed 2026-10-03 and accepted. None indicate a runtime crash.
#
# pattern_match (orchestrator): Tracker.fetch_issues_by_states/1 dispatches to a configurable
#   adapter; Dialyzer resolves it to the Memory adapter whose return type is narrower than the
#   callback, so the {:error, _} clause looks unreachable. It is correct for the GitHub/Linear adapters.
# pattern_match (github_webhook_controller:1): generated by `use Phoenix.Controller`.
#
# Scoped per file and per warning class so a new class of warning in these files still fails.
[
  {"lib/symphony_elixir/orchestrator.ex", :pattern_match},
  {"lib/symphony_elixir_web/controllers/github_webhook_controller.ex", :pattern_match}
]
