# Dialyzer warnings reviewed 2026-10-02 and accepted. None indicate a runtime crash.
#
# pattern_match_cov: intentional defensive fallback clauses (`_ -> {:error, ...}`) that the
#   success typings of the specs/callers make unreachable. They protect against upstream
#   payload drift (GitHub/Linear APIs) and are kept on purpose.
# call_without_opaque: URI/MapSet values flow through to_string/member? and OTP 28's
#   stricter opaque-type check complains; the calls are valid.
# pattern_match (orchestrator): Tracker.fetch_issues_by_states/1 spec is narrower than the
#   adapters' real returns; the {:error, _} clause is correct, the spec is what's loose.
# pattern_match (github_webhook_controller:1): generated by `use Phoenix.Controller`.
#
# Scoped per file and per warning class so a new class of warning in these files still fails.
[
  {"lib/symphony_elixir/github/auth.ex", :pattern_match_cov},
  {"lib/symphony_elixir/github/client.ex", :pattern_match_cov},
  {"lib/symphony_elixir/github/client.ex", :call_without_opaque},
  {"lib/symphony_elixir/orchestrator.ex", :pattern_match_cov},
  {"lib/symphony_elixir/orchestrator.ex", :pattern_match},
  {"lib/symphony_elixir/tracker.ex", :pattern_match_cov},
  {"lib/symphony_elixir_web/controllers/github_auth_controller.ex", :call_without_opaque},
  {"lib/symphony_elixir_web/controllers/github_webhook_controller.ex", :pattern_match}
]
